- sitemap-core.php
Hey @ftownes - please review this.
> Survey text and url changes

- sitemap-core.php
- sitemap-ui.php
Fix: Missing and broken URLs fixed in the plugin. For example: contact, feedback, Google and Bing notification.
> internal url fixes

- sitemap-core.php
Ticket: #10 
Purpose: Change survey message and form URL to capture new insights from our current users
Changes made:
- sitemap-core.php message body and URL changed
Effects:
- Users should start seeing the message about updated survey description and new form link on their admin control panel.
> survey message and form url changed based on github issue 10

- sitemap-loader.php
Ticket: [Rewrite Flush Needed After Disabling the plugin](https://github.com/Auctollo/google-sitemap-generator-premium/issues/1018)
Purpose:
- To flush database rewrite on deactivate plugin
Files changed: 
- sitemap-loader.php
Actions performed:
- Remove the rules from array which are added at time of activation
- flush the removed rules
> Flush sitemap rules after disabling the plugin

- sitemap-core.php
- sitemap-ui.php
Ticket: [V4: Change sitemap URL](https://github.com/Auctollo/google-sitemap-generator-premium/issues/1024)
Purpose:
- provide the custom name for the sitemap.xml fille
Files changed: 
- sitemap-core.php
- sitemap-ui.php
Actions performed:
- provided input for the filename
- Change name of file at the time of url generation
- Change the rewrite rule and delete old xml file
> Added support for custom file name for sitemap

- class-googlesitemapgeneratorstandardbuilder.php
- class-googlesitemapgeneratorui.php
- sitemap-core.php
Provided support for WordPress v6.0
> solved issues in wordpress version 6.0

- class-googlesitemapgeneratorloader.php
[#1231](https://github.com/Auctollo/google-sitemap-generator-premium/issues/1231)
> fixes in cross image size

- sitemap.php
[#1225](https://github.com/Auctollo/google-sitemap-generator-premium/issues/1225)
> added checks for console error

- sitemap.php
- upgrade-plugin.php
[#1234](https://github.com/Auctollo/google-sitemap-generator-premium/issues/1234)
> added support for wordpress version 4 and php version 7 and 8

- class-googlesitemapgeneratorloader.php
[#1239](https://github.com/Auctollo/google-sitemap-generator-premium/issues/1239)
> bug fix in enable auto update banner

- class-googlesitemapgeneratorloader.php
- class-googlesitemapgeneratorui.php
- sitemap-core.php
- sitemap.php
- fixed issue with disabling confliction seo plugins sitemaps, not it's disable sitemap option, not whole plugin
- added checking for user rights
-fixed generation of main sitemap url
> Disabling conflicts sitemap

- class-googlesitemapgeneratorloader.php
- class-googlesitemapgeneratorui.php
- sitemap-core.php
- sitemap.php
Changed plugin text domain name from **sitemap** to **google-sitemap-generator**
> change text domain name

- sitemap.php
remove wp_ajax_nopriv_disable_plugins
> fixed admin security issues

- class-googlesitemapgeneratorloader.php
> fixed sprintf fatal error

- class-googlesitemapgeneratorstandardbuilder.php
- sitemap-core.php
- upgrade-plugin.php
Fixed external sitemap
Fixed not found urls
> Improvements

- class-googlesitemapgeneratorloader.php
- sitemap.php
- upgrade-plugin.php
Users had problems with 404 urls in sub sitemaps after plugin update, created event for the url rules update on admin_init hook
> resolved 404 sub sitemap url issue after plugin update

- class-googlesitemapgeneratorloader.php
Wrong rewrite rules generated 404 sitemap pages, setup the correct values for rules
> resolved sitemap rewrite urls issue, changed test urls to the relevant

- class-googlesitemapgeneratorindexnow.php
- class-googlesitemapgeneratorloader.php
- sitemap.php
Improved the indexnow functionality, thanks to which now sites in multisite mode are also sent to the page index.
> resolved indexnow functionality for subsites in multisite mode

- class-googlesitemapgeneratorloader.php
- class-googlesitemapgeneratorstandardbuilder.php
- sitemap-core.php
The display of maps of products for categories and taxonomies with the dates of the last changes, the ability to set your own url address for the main map and submaps, support for the specified functionality in multisite mode, and the correctness of the misc map display have been implemented.
> Tasks forum topics

- class-googlesitemapgeneratorloader.php
- class-googlesitemapgeneratorui.php
Deactivate auto updating plugin when user click on reset button. Also anouncement appears in dashboard page.
> resolved deactivation auto-update plugin when reset settings

- class-googlesitemapgeneratorindexnow.php
- class-googlesitemapgeneratorui.php
- sitemap-core.php
resolved issue with html sitemap
removed unused Google ping
fixed fatal error after plugin setup
> resolved issues with html sitemap

- class-googlesitemapgeneratorloader.php
- class-googlesitemapgeneratorui.php
- sitemap-core.php
Resolved problems with ping functionality, now sitemaps urls are sent to search engin index correctly, fixed problem with float data by transformation to integer and added checking for array element existance .
> Latest release issues

- class-googlesitemapgeneratorloader.php
- sitemap-core.php
- sitemap.php
Added opportunity for user deactivate wordpress core sitemap by clicking on the button.
> resolved wordpress sitemap deactivation by user

- class-googlesitemapgeneratorloader.php
- sitemap.php
Improved rule for url generation and added update after plugin options submit what allow to set custom url address for main sitemap file.
> resolved possibility to set custom url for main sitemap file

- class-googlesitemapgeneratorstandardbuilder.php
- sitemap-core.php
Fixed error what appeared when was strated defug function and instead $end_time is displayed time spended for sitemap generation.
> resolved error due to incorrect type and time sitemap creating

- class-googlesitemapgeneratorui.php
- sitemap-core.php
- sitemap.php
Added default active status indexnow when first installation and auto activation for current users one time.
> resolved default active option indexnow

- class-googlesitemapgeneratorstandardbuilder.php
Made optimization query to database by taxonomies in main sitemap file.
> resolved decreased number taxonomies query to database

- class-googlesitemapgeneratorstandardbuilder.php
- class-googlesitemapgeneratorui.php
Is not changed status Wordpress Core Sitemap after reseting options, fixed problem with sitemap taxonomies pagination.
> Pre release issues

- class-googlesitemapgeneratorui.php
Hide message "Search engines haven't been notified yet. Write a post to let them know about your sitemap" when indexNow option is disabled.
> fixed information message about indexation

- class-googlesitemapgeneratorloader.php
- class-googlesitemapgeneratorstandardbuilder.php
- class-googlesitemapgeneratorui.php
- sitemap-core.php
Added memory calculation in KB and fixed custom name for main sitemap file in multisite mode.
> Limit memory and name sitemap

- class-googlesitemapgeneratorui.php
- sitemap-core.php
changed memory usage calculation algo
cleaned custom url and sitemap name fields after options reset
> changed memory usage calculation algo

- class-googlesitemapgeneratorindexnow.php
- class-googlesitemapgeneratorloader.php
- class-googlesitemapgeneratorui.php
- sitemap-core.php
- sitemap.php
- changed triggered hook from save_post to transition_post_status
- added message with API key value
- added post status detection
> improved indexnow functionality, replaced triggered hook

- class-googlesitemapgeneratorloader.php
rewrote logic in robots_txt filter
prevented appearance of core wordpress sitemap url
> Virtual robots.txt generation

- class-googlesitemapgeneratorloader.php
Improved checking for enabled robots.txt, installation yoast and all in one seo and added support more names for subsitemap of authors page.
> Uninstalled plugin error

- class-googlesitemapgeneratorloader.php
Was improved checking array element for existance and this additional code prevent appearence error.
> Fix prevented appearing error Undefined array key

- class-googlesitemapgeneratorstandardbuilder.php
The custom taxonomies created via CPT UI now are added to sitemap.
> Feat added custom taxonomy to sitemap

- class-googlesitemapgeneratorstandardbuilder.php
- class-googlesitemapgeneratorui.php
- sitemap-core.php
Added possibility for user include or exclude products subsitemap in main index page
> feature possibility to include/exclude products map

- class-googlesitemapgeneratorstandardbuilder.php
When outputting custom taxonomies in the sitemap, the get_terms() function was used, but it returned an "Invalid Taxonomy" error because the function was called before the taxonomy was registered.
Therefore, a new function was created that directly accesses the database and receives the necessary taxonomies.
> fix: Fixed issues where not all categories were displayed on the category sitemap page
